package sow.mvc.vista;

import sow.mvc.controlador.ControladorAyudante;

/**
 * Interfaz gráfica perteneciente al Ayudante.
 */
public class AyudanteJFrame extends javax.swing.JFrame implements Ayudante {

    /**
     * init compoents
     */
    public AyudanteJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        proposito = new javax.swing.JPanel();
        relajacion = new javax.swing.JPanel();
        motivacion = new javax.swing.JPanel();
        tecnicaPreguntas = new javax.swing.JPanel();

        javax.swing.GroupLayout propositoLayout = new javax.swing.GroupLayout(proposito);
        proposito.setLayout(propositoLayout);
        propositoLayout.setHorizontalGroup(
            propositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        propositoLayout.setVerticalGroup(
            propositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Importancia de un propósito", proposito);

        javax.swing.GroupLayout relajacionLayout = new javax.swing.GroupLayout(relajacion);
        relajacion.setLayout(relajacionLayout);
        relajacionLayout.setHorizontalGroup(
            relajacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        relajacionLayout.setVerticalGroup(
            relajacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Técnicas de relajación", relajacion);

        javax.swing.GroupLayout motivacionLayout = new javax.swing.GroupLayout(motivacion);
        motivacion.setLayout(motivacionLayout);
        motivacionLayout.setHorizontalGroup(
            motivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        motivacionLayout.setVerticalGroup(
            motivacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Motivación", motivacion);

        javax.swing.GroupLayout tecnicaPreguntasLayout = new javax.swing.GroupLayout(tecnicaPreguntas);
        tecnicaPreguntas.setLayout(tecnicaPreguntasLayout);
        tecnicaPreguntasLayout.setHorizontalGroup(
            tecnicaPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 674, Short.MAX_VALUE)
        );
        tecnicaPreguntasLayout.setVerticalGroup(
            tecnicaPreguntasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Técnica pregunta y respuesta", tecnicaPreguntas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setControlador(ControladorAyudante c) {
        //this.btn.addActionListener(e);
    }

    @Override
    public void iniciaVista() {
        setLocationRelativeTo(null);
        setVisible(true);
    }

    @Override
    public void error(String error) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void ejecucionCorrecta(String mensaje) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel motivacion;
    private javax.swing.JPanel proposito;
    private javax.swing.JPanel relajacion;
    private javax.swing.JPanel tecnicaPreguntas;
    // End of variables declaration//GEN-END:variables
}
