package sow.mvc.vista;

import javax.swing.JOptionPane;
import sow.mvc.controlador.ControladorEmociones;

/**
 * Interfaz gráfica correspondiente al registro de emociones.
 */
public class RegistroDeEmocionesJFrame extends javax.swing.JFrame implements RegistroDeEmociones {

    /**
     * InitComponents
     */
    public RegistroDeEmocionesJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        estadoAnimico = new javax.swing.JTextField();
        distractores = new javax.swing.JTextField();
        benefactores = new javax.swing.JTextField();
        guardarAmbienteJBtn = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();
        eAnimicoLabel = new javax.swing.JLabel();
        distraccionesLabel = new javax.swing.JLabel();
        benefactorLabel = new javax.swing.JLabel();
        backgroundEmociones1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        backgroundEmociones = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1080, 764));
        setMinimumSize(new java.awt.Dimension(1080, 764));
        setPreferredSize(new java.awt.Dimension(1080, 764));

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1080, 764));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1080, 764));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        estadoAnimico.setBackground(new java.awt.Color(152, 189, 204));
        estadoAnimico.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        estadoAnimico.setMargin(new java.awt.Insets(5, 15, 5, 5));
        jPanel2.add(estadoAnimico, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 230, 420, 40));

        distractores.setBackground(new java.awt.Color(152, 189, 204));
        distractores.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        distractores.setMargin(new java.awt.Insets(5, 15, 5, 5));
        jPanel2.add(distractores, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 297, 420, 40));

        benefactores.setBackground(new java.awt.Color(152, 189, 204));
        benefactores.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        benefactores.setMargin(new java.awt.Insets(5, 15, 5, 5));
        jPanel2.add(benefactores, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 378, 420, 40));

        guardarAmbienteJBtn.setText("Enviar datos");
        jPanel2.add(guardarAmbienteJBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 488, -1, -1));
        guardarAmbienteJBtn.setActionCommand(GUARDAR_AMBIENTE);

        tituloLabel.setBackground(new java.awt.Color(51, 51, 51));
        tituloLabel.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        tituloLabel.setText("Bienvenido, usted va a registrar las variables del entorno de su ultima nota");
        jPanel2.add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 26, -1, -1));

        eAnimicoLabel.setBackground(new java.awt.Color(51, 51, 51));
        eAnimicoLabel.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        eAnimicoLabel.setText("Mi estado anímico es");
        jPanel2.add(eAnimicoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 237, -1, -1));

        distraccionesLabel.setBackground(new java.awt.Color(51, 51, 51));
        distraccionesLabel.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        distraccionesLabel.setText("Al escribir me distrajo");
        jPanel2.add(distraccionesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 302, -1, -1));

        benefactorLabel.setBackground(new java.awt.Color(51, 51, 51));
        benefactorLabel.setFont(new java.awt.Font("Verdana", 1, 17)); // NOI18N
        benefactorLabel.setText("Algo bueno al escribir");
        jPanel2.add(benefactorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 384, -1, -1));

        backgroundEmociones1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backgroundEmociones.jpg"))); // NOI18N
        backgroundEmociones1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(backgroundEmociones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Registrar emcioón", jPanel2);

        backgroundEmociones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/backgroundEmociones.jpg"))); // NOI18N
        backgroundEmociones.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backgroundEmociones)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(backgroundEmociones)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Gestor de emociones", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundEmociones;
    private javax.swing.JLabel backgroundEmociones1;
    private javax.swing.JLabel benefactorLabel;
    private javax.swing.JTextField benefactores;
    private javax.swing.JLabel distraccionesLabel;
    private javax.swing.JTextField distractores;
    private javax.swing.JLabel eAnimicoLabel;
    private javax.swing.JTextField estadoAnimico;
    private javax.swing.JButton guardarAmbienteJBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * Setea el controlador del patron MVC.
     *
     * @param c Eventos de la vista que se pasan al (c)ontrolador.
     */
    @Override
    public void setControlador(ControladorEmociones c) {
        this.guardarAmbienteJBtn.addActionListener(c);
    }

    /**
     * Inicia la vista.
     */
    @Override
    public void iniciaVista() {
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     *
     * @param error Se trata de un String que quieres que aparezca en el JOption
     * Pane
     */
    @Override
    public void error(String error) {
        JOptionPane.showMessageDialog(this, "Ocurrio una excepción: " + error, "Información", JOptionPane.ERROR_MESSAGE);
    }

    /**
     *
     * @param mensaje
     */
    @Override
    public void ejecucionCorrecta(String mensaje) {
        ZMensajesJOptionPane.getMensajeEjecucionCorrecta(mensaje);
    }

    /**
     *
     * @return
     */
    @Override
    public String getEstadoAnimicoJText() {
        return estadoAnimico.getText();
    }

    /**
     *
     * @return
     */
    @Override
    public String getDistractoresJText() {
        return distractores.getText();
    }

    /**
     *
     * @return
     */
    @Override
    public String getBenefactoresJText() {
        return benefactores.getText();
    }

    @Override
    public void setEstadoAnimicoJText(String string) {
        estadoAnimico.setText(string);
    }

    @Override
    public void setDistractoresJText(String string) {
        distractores.setText(string);
    }

    @Override
    public void setBenefactoresJText(String string) {
        benefactores.setText(string);
    }

}
